//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanSach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookStoreEntities : DbContext
    {
        public BookStoreEntities()
            : base("name=BookStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<spThongKeDoanhThuTheLoaiTheoNam_Result> spThongKeDoanhThuTheLoaiTheoNam(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spThongKeDoanhThuTheLoaiTheoNam_Result>("spThongKeDoanhThuTheLoaiTheoNam", yearParameter);
        }
    
        public virtual ObjectResult<spThongKeDoanhThuTheoNam_Result> spThongKeDoanhThuTheoNam(Nullable<int> year)
        {
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spThongKeDoanhThuTheoNam_Result>("spThongKeDoanhThuTheoNam", yearParameter);
        }
    
        public virtual ObjectResult<spThongKeSoLuongSanPhamTheoThang_Result> spThongKeSoLuongSanPhamTheoThang(Nullable<int> thang)
        {
            var thangParameter = thang.HasValue ?
                new ObjectParameter("thang", thang) :
                new ObjectParameter("thang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spThongKeSoLuongSanPhamTheoThang_Result>("spThongKeSoLuongSanPhamTheoThang", thangParameter);
        }
    
        public virtual ObjectResult<ThongKeDoanhThuTheoThang_Result> ThongKeDoanhThuTheoThang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThongKeDoanhThuTheoThang_Result>("ThongKeDoanhThuTheoThang");
        }
    
        public virtual ObjectResult<Nullable<int>> ThongKeSoLuongSachTheoTheLoai()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ThongKeSoLuongSachTheoTheLoai");
        }
    }
}
